name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          libncurses5 \
          libstdc++6 \
          zlib1g-dev \
          libffi-dev \
          libssl-dev \
          openjdk-17-jdk \
          unzip \
          zip \
          git \
          wget \
          python3-pip

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Accept Android SDK licenses
      run: |
        mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
        yes | buildozer android update

    - name: Clean previous builds
      run: |
        rm -rf .buildozer
        buildozer android clean

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-kivy-app
        path: bin/*.apk
