name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache git zip unzip openjdk-17-jdk python3-pip libncurses6
        pip install --upgrade pip
        pip install buildozer cython

    - name: Generate buildozer.spec if missing
      run: test -f buildozer.spec || buildozer init

    - name: Accept Android SDK licenses & install tools
      run: |
        yes | sdkmanager --licenses
        sdkmanager "p
