name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache git zip unzip openjdk-17-jdk python3-pip libncurses5 coreutils
          pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

      - name: Configure buildozer.spec
        run: |
          if ! grep -q '^version' buildozer.spec; then
            echo "version = 0.1" >> buildozer.spec
          fi
          if grep -q '^android.arch =' buildozer.spec; then
            sed -i 's/^android.arch =.*/# android.arch removed/' buildozer.spec
            echo "android.archs = armeabi-v7a" >> buildozer.spec
          fi

      - name: Initialize Buildozer
        run: buildozer android clean

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: bin/*.apk
