name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache git zip unzip openjdk-17-jdk python3-pip libncurses6
        pip install --upgrade pip
        pip install buildozer cython

    - name: Initialize Buildozer (generate .buildozer folder)
      run: buildozer android clean

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses || true
      env:
        ANDROID_HOME: $HOME/.buildozer/android/platform/android-sdk

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app-apk
        path: bin/*.apk
